[versions]
androidGradlePlugin = "8.1.1"
ktx = "1.9.0"

[libraries]
androidx-ktx = {group="androidx.core",name="core-ktx",version.ref="ktx"}

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }